### ISSUE TITLE
Error running TIPseqHunterPipelineJarSomatic.sh

### ISSUE THREAD

**Issue by lxhuang7** [FenyoLab/TIPseqHunter#2]
Dear TIPseqHunter authors,

I would appreciate if you could help solve this error I got from TIPseqHunterPipelineJarSomatic.sh after running the TIPseqHunter2PipelineJar.sh pipeline. Is that due to the new TIPseqHunter2PipelineJar.sh pipeline or something else?

If I set tipseqjar=$PROJDIR/src/TIPseqHunter/TIPseqHunter2.jar, I got the following message:

-------------
repred-path=/gpfs/data/results/S01/model
repred-file=_001.fastq.gz.wsize100.regwsize1.minreads1.clip1.clipflk5.mindis150.l1ta.uniqgs.bed.csinfo.lm.l1hs.svm.pred
control-path=/gpfs/data/results/S01/TRLocator
control-file=_001.fastq.gz.cleaned.fastq.pcsort.bam.w100.minreg1.mintag1.bed
Error: Could not find or load main class org.nyumc.TIPseqHunter_20150727.P6_IdentificationOfExistingMobileDNASite
Error: Could not find or load main class org.nyumc.TIPseqHunter_20150727.P6_IdentificationOfExistingMobileDNASite
Error: Could not find or load main class org.nyumc.TIPseqHunter_20150727.PP1_FindMatchInControl
Error: Could not find or load main class org.nyumc.TIPseqHunter_20150727.PP2_SelectionOfTumorSpecificInsertion
Error: Could not find or load main class org.nyumc.TIPseqHunter_20150727.P15_AnnotateOutputUsingRefseqFile
-----------------

If I set tipseqjar=$PROJDIR/src/TIPseqHunter/TIPseqHunter.jar, I got the following message and the empty .selected file.

-----------------
repred-path=/gpfs/data/results/S01/model
repred-file=_001.fastq.gz.wsize100.regwsize1.minreads1.clip1.clipflk5.mindis150.l1ta.uniqgs.bed.csinfo.lm.l1hs.svm.pred
control-path=/gpfs/data/results/S01/TRLocator
control-file=_001.fastq.gz.cleaned.fastq.pcsort.bam.w100.minreg1.mintag1.bed
P6_IdentificationOfExistingMobileDNASite starts.
Reading control file ...
Reading this file ...
P6_IdentificationOfExistingMobileDNASite ends.
P6_IdentificationOfExistingMobileDNASite starts.
Reading control file ...
Reading this file ...
P6_IdentificationOfExistingMobileDNASite ends.
PP1_FindMatchInControl starts.
Reading control file ...
Reading this file ...
PP1_FindMatchInControl ends.
PP2_SelectionOfTumorSpecificInsertion starts.
java.lang.NumberFormatException: For input string: "Predicted Negative Insertions"
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
        at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
        at java.lang.Double.parseDouble(Double.java:538)
        at java.lang.Double.valueOf(Double.java:502)
        at org.nyumc.TIPseqHunter_20150727.PP2_SelectionOfTumorSpecificInsertion.main(PP2_SelectionOfTumorSpecificInsertion.java:138)
PP2_SelectionOfTumorSpecificInsertion ends.
P15_AnnotateOutputUsingRefseqFile starts.
Reading annotation file ...
Reading list file ...
P15_AnnotateOutputUsingRefseqFile ends.
-------------------

Thanks in advance!
Lei

**Comment by Zuojian-Tang** [comment]
Sorry for the late response.
TIPseqHunterPipelineJarSomatic.sh is only applicable to TIPseqHunter version 1.0. We do not have similar script of post-selection for TIPseqHunter version 2.0 now. I suggest you to use TIPseqHunter version 1.0 if your data set is not large in order to use post-selection script. Sorry for the inconvenience.

**Comment by lxhuang7** [comment]
Thank you very much!
